# -*- coding: utf-8 -*-
"""Cifar10DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wJFt72Ly18XFvo3GGTv768tKDa5mN7nn
"""

import tensorflow as tf
from tensorflow.keras.datasets import cifar10
import matplotlib.pyplot as plt
import numpy as np

(X_train,Y_train), (X_test,Y_test) = cifar10.load_data()

X_train = X_train / 255
X_test = X_test / 255

model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(32,32,3)),
    tf.keras.layers.Dense(128,activation="relu"),
    tf.keras.layers.Dense(10,activation="softmax")
])

model.compile(
    optimizer= "adam",
    loss ="sparse_categorical_crossentropy",
    metrics = ["accuracy"]
)

model.fit(X_train,Y_train,epochs=5)

prediction = model.predict(X_test)

plt.imshow(X_test[30], cmap="Blues")
plt.title("predicted:" [np.argmax(prediction[30])])
plt.axis("off")
plt.show()

